#!/usr/bin/env bash
# demo-failover.sh — end-to-end failover demo (Task T046, Phase 7).
#
# Starts chain 1 with TWO mock upstreams (primary :19545, secondary :19547),
# runs the gateway with fast prober/circuit settings so failover is visible
# within seconds, then walks through: read via primary -> inject 500 on the
# primary -> poll reads until they succeed via the secondary -> restore the
# primary. See also scripts/demo.sh.
#
# Usage: ./scripts/demo-failover.sh   (or `make demo-failover`)

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)/bin"
GATEWAY_BIN="$BIN_DIR/gateway"
MOCKUP_BIN="$BIN_DIR/mockupstream"

# Ports, fixed by the Makefile / quickstart contract:
GATEWAY_URL="http://localhost:8545"
METRICS_URL="http://localhost:9090"
PRIMARY_URL="http://localhost:19545"     # matches Makefile LOAD_DIRECT_URL
SECONDARY_URL="http://localhost:19547"

DEMO_DIR=""
GATEWAY_PID=""
PRIMARY_PID=""
SECONDARY_PID=""

die() {
  echo "error: $*" >&2
  exit 1
}

cleanup() {
  trap - INT TERM EXIT
  # Stop the gateway first, then the mocks.
  for pid in "$GATEWAY_PID" "$PRIMARY_PID" "$SECONDARY_PID"; do
    if [ -n "${pid:-}" ]; then
      kill "$pid" 2>/dev/null || true
    fi
  done
  if [ -n "$DEMO_DIR" ]; then
    rm -rf "$DEMO_DIR"
  fi
  echo "demo-failover stopped"
}
trap cleanup INT TERM EXIT

# wait_http URL TIMEOUT_SECONDS LABEL — poll a URL until it answers with
# HTTP 200 (used for mock /_health and gateway /healthz readiness).
wait_http() {
  local url="$1" timeout_secs="$2" label="$3"
  local deadline=$((SECONDS + timeout_secs))
  until curl -sf --max-time 2 "$url" >/dev/null 2>&1; do
    if [ "$SECONDS" -ge "$deadline" ]; then
      die "timed out after ${timeout_secs}s waiting for ${label} at ${url}"
    fi
    sleep 0.5
  done
  echo "${label}: ready"
}

# ctl MODE URL — drive the mock upstream fault-injection control endpoint.
ctl() {
  curl -s --max-time 5 -X POST "$2/_ctl" -H 'Content-Type: application/json' \
    -d "{\"mode\":\"$1\"}"
  echo
}

[ -x "$GATEWAY_BIN" ] || die "$GATEWAY_BIN not found — build it first: make bin/gateway bin/mockupstream (or just: make demo-failover)"
[ -x "$MOCKUP_BIN" ] || die "$MOCKUP_BIN not found — build it first: make bin/gateway bin/mockupstream (or just: make demo-failover)"

# --- mock upstreams (chain 1: primary + secondary) ---------------------------
echo "starting chain 1 mock upstreams: primary on :19545, secondary on :19547"
"$MOCKUP_BIN" -chain-id 1 -listen :19545 &
PRIMARY_PID=$!
"$MOCKUP_BIN" -chain-id 1 -listen :19547 &
SECONDARY_PID=$!

# --- temporary gateway config ------------------------------------------------
# Fast prober + circuit settings so the primary is marked unhealthy and the
# breaker opens within a few seconds of the injected failure.
DEMO_DIR="$(mktemp -d "${TMPDIR:-/tmp}/gateway-demo-failover.XXXXXX")" || die "mktemp failed"
CONFIG="$DEMO_DIR/config.yaml"
cat >"$CONFIG" <<EOF
# Temporary config generated by scripts/demo-failover.sh; removed on exit.
server:
  listen: ":8545"
  metrics_listen: ":9090"
prober:
  interval: 2s
  timeout: 1s
  fail_threshold: 2
circuit:
  fail_threshold: 2
  cooldown: 5s
chains:
  - chain_id: "1"
    adapter: ethereum
    upstreams:
      - name: primary
        url: http://localhost:19545
      - name: secondary
        url: http://localhost:19547
EOF

# --- gateway -----------------------------------------------------------------
echo "starting gateway (-config $CONFIG)"
"$GATEWAY_BIN" -config "$CONFIG" -log-level info &
GATEWAY_PID=$!

wait_http "$PRIMARY_URL/_health" 10 "primary mock upstream"
wait_http "$SECONDARY_URL/_health" 10 "secondary mock upstream"
wait_http "$METRICS_URL/healthz" 15 "gateway"

# --- step 1: read via primary -------------------------------------------------
echo
echo "== step 1: eth_chainId via chain 1 (served by the primary) =="
RESP="$(curl -s --max-time 5 "$GATEWAY_URL" -H 'Content-Type: application/json' \
  -H 'X-Chain-Id: 1' \
  -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}')"
echo "response: $RESP"

# --- step 2: break the primary ------------------------------------------------
echo
echo "== step 2: inject failure into the primary (POST /_ctl mode=500) =="
ctl 500 "$PRIMARY_URL"
echo "primary injected failure: $PRIMARY_URL now answers 500"

# --- step 3: poll reads until failover is visible ------------------------------
echo
echo "== step 3: polling eth_chainId every 2s — reads keep succeeding via the secondary =="
echo "(prober interval 2s + circuit fail_threshold 2 => failover visible within a few seconds)"
for i in $(seq 1 15); do
  RESP="$(curl -s --max-time 5 "$GATEWAY_URL" -H 'Content-Type: application/json' \
    -H 'X-Chain-Id: 1' \
    -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}')"
  echo "attempt $i: $RESP"
  sleep 2
done
echo
echo "read requests (eth_chainId) kept succeeding after the primary broke:"
echo "safe/read-only methods are retried and failed over to the secondary upstream."
echo "write methods (e.g. eth_sendRawTransaction) are NEVER auto-retried:"
echo "they are attempted exactly once, on the selected upstream."
echo
echo "gateway view of upstream health and circuit state (0=closed, 1=open, 2=half-open):"
curl -s --max-time 5 "$METRICS_URL/metrics" | grep -E 'gateway_upstream_up|gateway_upstream_circuit_state' || true

# --- step 4: recover the primary -----------------------------------------------
echo
echo "== step 4: restore the primary (POST /_ctl mode=ok) =="
ctl ok "$PRIMARY_URL"
echo "primary restored — the prober (interval 2s) marks it healthy again within a few probe intervals"
sleep 6
RESP="$(curl -s --max-time 5 "$GATEWAY_URL" -H 'Content-Type: application/json' \
  -H 'X-Chain-Id: 1' \
  -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}')"
echo "post-recovery eth_chainId: $RESP"

# --- run until Ctrl-C ----------------------------------------------------------
echo
echo "demo-failover running — press Ctrl-C to stop"
wait
