#!/usr/bin/env bash
# demo.sh — one-command local demo (Task T046, Phase 7).
#
# Starts two mock upstreams (chain 1 on :19545, chain 8453 on :19546) plus the
# gateway on :8545 (JSON-RPC) / :9090 (metrics + healthz), prints the runnable
# verification commands from quickstart.md (§1/§2), runs one self-check for
# chain 8453, then keeps running until Ctrl-C. See also scripts/demo-failover.sh.
#
# Usage: ./scripts/demo.sh   (or `make demo`, which builds the binaries first)

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)/bin"
GATEWAY_BIN="$BIN_DIR/gateway"
MOCKUP_BIN="$BIN_DIR/mockupstream"

# Gateway ports, fixed by the Makefile / quickstart contract:
GATEWAY_URL="http://localhost:8545"
METRICS_URL="http://localhost:9090"
MOCK_CHAIN1_URL="http://localhost:19545"  # matches Makefile LOAD_DIRECT_URL
MOCK_CHAIN8453_URL="http://localhost:19546"

DEMO_DIR=""
GATEWAY_PID=""
MOCK1_PID=""
MOCK8453_PID=""

die() {
  echo "error: $*" >&2
  exit 1
}

cleanup() {
  trap - INT TERM EXIT
  # Stop the gateway first, then the mocks.
  for pid in "$GATEWAY_PID" "$MOCK1_PID" "$MOCK8453_PID"; do
    if [ -n "${pid:-}" ]; then
      kill "$pid" 2>/dev/null || true
    fi
  done
  if [ -n "$DEMO_DIR" ]; then
    rm -rf "$DEMO_DIR"
  fi
  echo "demo stopped"
}
trap cleanup INT TERM EXIT

# wait_http URL TIMEOUT_SECONDS LABEL — poll a URL until it answers with
# HTTP 200 (used for mock /_health and gateway /healthz readiness).
wait_http() {
  local url="$1" timeout_secs="$2" label="$3"
  local deadline=$((SECONDS + timeout_secs))
  until curl -sf --max-time 2 "$url" >/dev/null 2>&1; do
    if [ "$SECONDS" -ge "$deadline" ]; then
      die "timed out after ${timeout_secs}s waiting for ${label} at ${url}"
    fi
    sleep 0.5
  done
  echo "${label}: ready"
}

[ -x "$GATEWAY_BIN" ] || die "$GATEWAY_BIN not found — build it first: make bin/gateway bin/mockupstream (or just: make demo)"
[ -x "$MOCKUP_BIN" ] || die "$MOCKUP_BIN not found — build it first: make bin/gateway bin/mockupstream (or just: make demo)"

# --- mock upstreams ----------------------------------------------------------
echo "starting mock upstreams: chain 1 on :19545, chain 8453 on :19546"
"$MOCKUP_BIN" -chain-id 1 -listen :19545 &
MOCK1_PID=$!
"$MOCKUP_BIN" -chain-id 8453 -listen :19546 &
MOCK8453_PID=$!

# --- temporary gateway config ------------------------------------------------
DEMO_DIR="$(mktemp -d "${TMPDIR:-/tmp}/gateway-demo.XXXXXX")" || die "mktemp failed"
CONFIG="$DEMO_DIR/config.yaml"
cat >"$CONFIG" <<EOF
# Temporary config generated by scripts/demo.sh; removed when the demo stops.
server:
  listen: ":8545"
  metrics_listen: ":9090"
chains:
  - chain_id: "1"
    adapter: ethereum
    upstreams:
      - name: mock-1
        url: http://localhost:19545
  - chain_id: "8453"
    adapter: base
    upstreams:
      - name: mock-8453
        url: http://localhost:19546
EOF

# --- gateway -----------------------------------------------------------------
echo "starting gateway (-config $CONFIG)"
"$GATEWAY_BIN" -config "$CONFIG" -log-level info &
GATEWAY_PID=$!

wait_http "$MOCK_CHAIN1_URL/_health" 10 "mock upstream chain 1"
wait_http "$MOCK_CHAIN8453_URL/_health" 10 "mock upstream chain 8453"
wait_http "$METRICS_URL/healthz" 15 "gateway"

# --- banner with runnable commands (quickstart.md §1/§2) ---------------------
cat <<EOF

======================================================================
 multichain-rpc-gateway demo
----------------------------------------------------------------------
 gateway JSON-RPC : $GATEWAY_URL
 metrics + healthz: $METRICS_URL
 mock chain 1     : $MOCK_CHAIN1_URL   (eth_chainId -> "0x1")
 mock chain 8453  : $MOCK_CHAIN8453_URL (eth_chainId -> "0x2105")
----------------------------------------------------------------------
 try these:

 # US1: chain 8453 (Base) — expect result "0x2105"
 curl -s localhost:8545 -H 'Content-Type: application/json' \\
   -H 'X-Chain-Id: 8453' \\
   -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}'

 # US1: unknown chain — expect error -32000, not forwarded
 curl -s localhost:8545 -H 'X-Chain-Id: 999' \\
   -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":2}'

 # US2: mixed-chain batch — element 1 -> chain 1, element 2 -> 8453
 #      override via x-chain-id, element 3 -> notification (no output)
 curl -s localhost:8545 -H 'Content-Type: application/json' -H 'X-Chain-Id: 1' \\
   -d '[{"jsonrpc":"2.0","method":"eth_chainId","id":1},
        {"jsonrpc":"2.0","method":"eth_chainId","id":2,"x-chain-id":"8453"},
        {"jsonrpc":"2.0","method":"eth_subscribe"}]'

 # US4: metrics (gateway_requests_total / gateway_upstream_up / ...)
 curl -s localhost:9090/metrics | grep gateway_

 # healthz
 curl -s localhost:9090/healthz

 press Ctrl-C to stop the demo
======================================================================

EOF

# --- self-check ---------------------------------------------------------------
echo "self-check: eth_chainId via chain 8453 ..."
RESP="$(curl -s --max-time 5 "$GATEWAY_URL" -H 'Content-Type: application/json' \
  -H 'X-Chain-Id: 8453' \
  -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}')"
echo "response: $RESP"
if printf '%s' "$RESP" | grep -q '0x2105'; then
  echo "self-check passed (chain 8453 answered with chainId \"0x2105\")"
else
  echo "error: self-check failed — expected chainId \"0x2105\" in the response above" >&2
  exit 1
fi

# --- run until Ctrl-C ----------------------------------------------------------
echo
echo "demo running — press Ctrl-C to stop"
wait
